// frontend/src/routes/mastery/+page.svelte
<!--
  @component
  ## Mastery Page
  Visualize the masteries of a player
-->
<script lang="ts">
    import type { MasteryDto, SummonerDto } from '$lib/types'
    import { styles } from '$lib/config'
    import { parse_k_num } from '$lib/utils'
    import { playersContext } from '$lib/context/players'
    import { Container, EmptyPlayers, Image, ProfileImg } from '$lib/components'

    // Context
    let _players: SummonerDto[] = []
    playersContext.subscribe(players => (_players = players))

    function totalMasteries(masteries: MasteryDto[]) {
        return masteries.reduce((acc, curr) => acc + curr.points, 0)
    }
</script>

{#if _players.length}
    <Container title="Mastery" description="Your 7 champions with most points">
        <div class="grid gap-4 2xl:grid-cols-2">
            {#each _players as player}
                <div class={`p-2 m-2 ${styles.card} ${styles.foreground} md:grid grid-cols-4`}>
                    <div class="flex items-center">
                        <ProfileImg image={player.image} level={player.level} />
                        <div class="flex flex-col">
                            <h2 class="text-xl">{player.alias}</h2>
                            {#if totalMasteries(player.masteries)}
                                <h4>{parse_k_num(totalMasteries(player.masteries), 0, false)}</h4>
                            {:else}
                                <span>No data</span>
                            {/if}
                        </div>
                    </div>
                    <div class="col-span-3 grid grid-cols-4 sm:grid-cols-7">
                        {#each player.masteries.slice(0, 7) as mastery}
                            <div class="p-2 text-center">
                                <span>
                                    {mastery.points > 100000 ? '🔥' : ''}
                                    {parse_k_num(mastery.points, 0, true)}
                                </span>
                                <div class="flex items-center justify-center">
                                    <div class="relative flex h-24 w-16 justify-center">
                                        <div class="t-0 r-0 absolute">
                                            <div class="relative h-28 w-16 rounded">
                                                <Image image={'/images/mastery/mastery_' + mastery.level + '.png'} />
                                            </div>
                                        </div>
                                        <div class="t-0 r-0 absolute">
                                            <div class="relative h-16 w-16 rounded">
                                                <Image image={mastery.image} />
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {/each}
                    </div>
                </div>
            {/each}
        </div>
    </Container>
{:else}
    <EmptyPlayers />
{/if}

// pages/mastery.tsx
import React, { useContext } from 'react'
import { Mastery } from '../interfaces/player'
import { styles } from '../styles/styles.config'
import { parse_k_num } from '../utils'
import { Container, EmptyPlayers, PlayerImg } from '../components'
import { PlayersContext } from '../hooks/PlayersContext'

// ┌────────────────┐
// │ MASTERIES PAGE:│
// └────────────────┘
// Visualize each player in a table
// Each row of the table is a champ with his stats
export default function Masteries() {
    const { players } = useContext(PlayersContext)

    if (!players || players.length === 0) {
        return <EmptyPlayers />
    }

    return (
        <Container title={'Mastery'} description={'Your 7 champions with most points'}>
            <div className='grid gap-4 xl:grid-cols-2'>
                {players.map((player, idx_player) => {
                    let total_masteries = 0
                    player.masteries.map((mastery: Mastery) => (total_masteries += mastery.points))

                    return (
                        <div key={idx_player} className={`p-2 m-2 ${styles.card} ${styles.foreground} md:grid grid-cols-4`}>
                            <div className='flex items-center'>
                                <PlayerImg image={player.image} alias={player.alias} level={player.level} />
                                <div className='flex flex-col'>
                                    <h2 className='text-xl'>{player.alias}</h2>
                                    <h4>{parse_k_num(total_masteries, 0, false)}</h4>
                                </div>
                            </div>
                            <div className='col-span-3 grid grid-cols-4 sm:grid-cols-7'>
                                {player.masteries.map((mastery: Mastery, idx_mastery: number) => (
                                    <div key={idx_mastery} className='p-2 text-center'>
                                        <span>
                                            {mastery.points > 100000 ? '🔥' : ''}
                                            {parse_k_num(mastery.points, 0, true)}
                                        </span>
                                        <div className='relative h-24 flex justify-center'>
                                            <img
                                                className='w-14 rounded absolute t-0 r-0'
                                                src={'/images/mastery_' + mastery.level + '.png'}
                                                alt={mastery.name}
                                            />
                                            <img className='w-14 rounded absolute t-0 r-0' src={mastery.image} alt={mastery.name} />
                                        </div>
                                    </div>
                                ))}
                            </div>
                        </div>
                    )
                })}
            </div>
        </Container>
    )
}
